# Generated by Django 3.0.2 on 2020-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200123_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.IntegerField(help_text='An engine volume. Eg 2.2, 5.6 etc.', null=True),
        ),
    ]
