# Generated by Django 3.0.2 on 2020-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_engine_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsubtype',
            name='code',
            field=models.CharField(help_text='The fuel subtype code. Must be unique ', max_length=64),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='code',
            field=models.CharField(choices=[(0, 'Diesel'), (1, 'Benzin'), (2, 'Gas')], default=0, help_text='Fuel Type. Diesel | Benzing | Gas | Spiritus, etc. Short code for it', max_length=64),
        ),
    ]
