# Generated by Django 3.0.2 on 2020-01-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200123_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='code',
            field=models.CharField(help_text='Fuel Type. Diesel | Benzing | Gas | Spiritus, etc. Short code for it', max_length=64),
        ),
    ]
