# Generated by Django 3.0.2 on 2020-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200123_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fueltype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(help_text='A date of the payment. Should be ISO string', null=True),
        ),
    ]
