# Generated by Django 3.0.2 on 2020-01-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200123_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fuel_type',
            field=models.ForeignKey(help_text='Fuel type, Diesel, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FuelType'),
        ),
    ]
