# Generated by Django 3.0.2 on 2020-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='odometer',
            field=models.IntegerField(blank=True, help_text='The car current odometer value when payment was made', null=True),
        ),
    ]
