# Generated by Django 3.0.2 on 2020-01-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200123_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_odometer',
            field=models.IntegerField(blank=True, help_text='The car current odometer. Updates automatically at each payment when you fill the odometer field ', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='An engine volume. Eg 2.2, 5.6 etc.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='initial_odometer',
            field=models.IntegerField(blank=True, help_text='The car initial odometer', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, help_text='A payment commenct', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, help_text='A date of the payment. Should be ISO string', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fuel_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='An amount of the fuel (Litre).', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fuel_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A fuel price. Total price can be calculated automatically if it is a Fuel payment ', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fuel_subtype',
            field=models.ForeignKey(blank=True, help_text='Fuel subtype, 95, 92, Extra, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FuelSubType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fuel_type',
            field=models.ForeignKey(blank=True, help_text='Fuel type, Diesel, etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FuelType'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='station',
            field=models.ForeignKey(blank=True, help_text='A station where payment had been made', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Station'),
        ),
    ]
